### ISSUE TITLE
instalation fail

### ISSUE THREAD

**Issue by zloychan** [FooBallZ/pulsar#16]
Step 21/28 : RUN go get github.com/zmap/zdns/zdns
 ---> Running in a1d3c565ef0e
# github.com/zmap/zdns/modules/miekg
src/github.com/zmap/zdns/modules/miekg/miekg.go:279:12: s.Client.LocalAddr undefined (type *dns.Client has no field or method LocalAddr)
src/github.com/zmap/zdns/modules/miekg/miekg.go:292:12: s.Client.LocalAddr undefined (type *dns.Client has no field or method LocalAddr)

Failed to build docker containers.

 - OS: ubuntu 18.02 bionic

**Comment by 0x0FB0** [comment]
Noticed it yesterday, zdns package changed somehow.
Just merged dev branch, should be working now.

Needed to change
```
RUN go get github.com/zmap/zdns/zdns
```
to
```
RUN git clone https://github.com/zmap/zdns
RUN cd zdns/zdns && go build .
WORKDIR /opt/
```

in sandbox_storage/Dockerfile
