### ISSUE TITLE
Bad Request (400)

### ISSUE THREAD

**Issue by ghost** [FooBallZ/pulsar#2]
Hi,

After running docker-compose up, I receive a Bad Request (400) when surfing to the https://ip:8443/.

Let me know if you need any debug files.

**Comment by 0x0FB0** [comment]
Hello faun88,
Many usefull informations can be found in output of install script or docker-compose up. Check for any errors there.

Please send me output of `docker-compose exec web cat /var/log/nginx/error.log` command so I can get more details.

See TROUBLESHOOTING.md for guides on how to debug the issue.

**Comment by cybertron10** [comment]
Hi,

Same 400 error.

root@kali:~# docker-compose exec web cat /var/log/nginx/error.log
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

**Comment by cybertron10** [comment]
Hi,

Problem solved just add https:// so the url will be
https://localhost:8443/

**Comment by 0x0FB0** [comment]
Closing as no information have been provoded on the issue.
Assuming it was resolved. Issue can be reopened if needed.

**Comment by BBerastegui** [comment]
Hey @FooBallZ I came to this issue because I have the same error and I'm now trying to find out what happened.

The `error.log` file is empty in the web container.
The `access.log` is just returning the 400 that I see:
```
[REDACTED] - - [31/Mar/2020:17:33:45 +0000] "GET / HTTP/1.1" 400 154 "-" "Mozilla/5.0 [REDACTED] Chrome/80.0.3987.122 Safari/537.36"
```

And the log of the docker-compose is just completely empty after each request.

Cheers!

**Comment by BBerastegui** [comment]
Got it.

As indicated in the `TROUBLESHOOT.md` (as you pointed too) you have to add your hostname to the `allowed_hosts` in `portal/portal/settings.py` :D

Works now, for future references, I leave this comment here.

**Comment by snappyJack** [comment]
> 
> 
> Hi,
> 
> Problem solved just add https:// so the url will be
> https://localhost:8443/

Same 400 error,I add https:// but didn't work,what else did you do?
