### ISSUE TITLE
Document Update needed for kitploit website

### ISSUE THREAD

**Issue by katesaikishore** [FooBallZ/pulsar#20]
In kitploit the GitHub URL links are wrong 
They are leading us to other git repo.
please correct them.

![Screenshot 2020-04-01 at 8 33 51 AM](https://user-images.githubusercontent.com/10182914/78095018-960e7b00-73f3-11ea-9583-ea894645f46f.png)

**Comment by 0x0FB0** [comment]
Please use only official repository. I have no affiliation with this website at all.
