### ISSUE TITLE
hey devloper i have made a video describing how to install pulsar in linux . if you want to add it in the github page the link is 

### ISSUE THREAD

**Issue by gamingflexer** [FooBallZ/pulsar#22]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gamingflexer** [comment]
https://www.youtube.com/watch?v=AwCwmf7qfEk

**Comment by 0x0FB0** [comment]
Looks great! :)

I would be more than happy to add it, as long as you will change "Download" link in description to the proper one.

Right now it is set to https://linkvertise.com/49163/pulsardownload which looks very spammy to me ;)

**Comment by 0x0FB0** [comment]
Hey,
I've double checked the video and links in the description, as I've not found anything malicious I've decided to add link to the README.
Thanks!

**Comment by gamingflexer** [comment]
Thanks too
