### ISSUE TITLE
allow access from none localhost 

### ISSUE THREAD

**Issue by royharoush** [FooBallZ/pulsar#23]
I've been trying to allow access to this system from outside localhost by modifying porta/porta/settings.py "allowed hosts" array. 
 
![image](https://user-images.githubusercontent.com/8113056/78459901-26371380-76c5-11ea-81c9-562912398f54.png)

When CURLing inside from the localhost (an ec2 instance) I see it's supposedly working (guessing from the redirect). 
![image](https://user-images.githubusercontent.com/8113056/78459942-7ca45200-76c5-11ea-94ae-a72cab160e8c.png)

**Describe alternatives you've considered**
either instructions on how to make pulsar accessible from outside the machine or or setup option for that. 

Thanks,
Roy

**Comment by 0x0FB0** [comment]
Instruction is already there in TROUBLESHOOTING.md file.
*In case you would like to configure external access, you can add additional ALLOWED_HOSTS in `portal/portal/settings.py` and rebuild web container.*

**Comment by 0x0FB0** [comment]
Let me know if you still have issues with those settings in place

**Comment by royharoush** [comment]
![image](https://user-images.githubusercontent.com/8113056/78460536-47e6c980-76ca-11ea-8039-3aa6c68b953c.png)


This is what I did , both locally , then down ,build, up.
I also tried with just 0.0.0.0 in the array. 
didn't work. 
So i forked it and changed in my own repo, (reinstalled on a different machine..)and still didn't work.

**Comment by 0x0FB0** [comment]
Interesting, I'll figure it out and let you know

**Comment by 0x0FB0** [comment]
From my side it works as expected.
May be stupid question, but are you sure you are using https:// proto?

settings.py ALLOWED_HOSTS:
```
ALLOWED_HOSTS = ['pulsar.io','127.0.0.1', 'localhost']
```

![allowed_hosts](https://user-images.githubusercontent.com/25950053/78462485-ccd5e100-76d2-11ea-96e3-c9f6575e5de0.PNG)

I have no further ideas, can you run `docker-compose exec web tail -f /var/log/nginx/`, try accessing your AWS instance on both IP and domain and send me the output?
This will help me understand what might be happening.

**Comment by royharoush** [comment]
I've been trying both http and https.
I'll try to get around it this week. 
But from looking at your example .. it seems like it's looking at the host header, so maybe i should use the IP of the system instead of 0.0.0.0.

**Comment by royharoush** [comment]
it works, i added the public ip instead of 0.0.0.0. 
should update the documentation :)
thanks !
