### ISSUE TITLE
Broken Connection Between web and db for auth

### ISSUE THREAD

**Issue by mrdavi5** [FooBallZ/pulsar#25]
> :warning: Make sure you have seen TROUBLESHOOTING.md

**Describe the bug**

Following the .\install.sh and copied the creds. once the docker containers I get this within the logs. I can see the web log in but if I log in with the real or fake creds I get a server error. the logs show the db creds are working. 
I have tried docker up build and down also. 

web        | The above exception was the direct cause of the following exception:
web        | 
web        | Traceback (most recent call last):
web        |   File "manage.py", line 22, in <module>
web        |     main()
web        |   File "manage.py", line 18, in main
web        |     execute_from_command_line(sys.argv)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
web        |     utility.execute()
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
web        |     self.fetch_command(subcommand).run_from_argv(self.argv)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
web        |     self.execute(*args, **cmd_options)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
web        |     self.check()
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
web        |     all_issues = self._run_checks(
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 63, in _run_checks
web        |     issues = run_checks(tags=[Tags.database])
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
web        |     new_errors = check(app_configs=app_configs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/database.py", line 10, in check_database_backends
web        |     issues.extend(conn.validation.check(**kwargs))
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/validation.py", line 9, in check
web        |     issues.extend(self._check_sql_mode(**kwargs))
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/validation.py", line 13, in _check_sql_mode
web        |     with self.connection.cursor() as cursor:
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 260, in cursor
web        |     return self._cursor()
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 236, in _cursor
web        |     self.ensure_connection()
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web        |     self.connect()
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
web        |     raise dj_exc_value.with_traceback(traceback) from exc_value
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web        |     self.connect()
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
web        |     self.connection = self.get_new_connection(conn_params)
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 233, in get_new_connection
web        |     return Database.connect(**conn_params)
web        |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 84, in Connect
web        |     return Connection(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 171, in __init__
web        |     super(Connection, self).__init__(*args, **kwargs2)
web        | django.db.utils.OperationalError: (1045, "Access denied for user 'pulsar_db_user'@'web.pulsar_default' (using password: YES)")
web        | 
web        | [+] Adding Django admin user...
web        | 
web        | Traceback (most recent call last):
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web        |     self.connect()
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
web        |     self.connection = self.get_new_connection(conn_params)
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 233, in get_new_connection
web        |     return Database.connect(**conn_params)
web        |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 84, in Connect
web        |     return Connection(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 171, in __init__
web        |     super(Connection, self).__init__(*args, **kwargs2)
web        | MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'pulsar_db_user'@'web.pulsar_default' (using password: YES)")

**Expected behavior**
Login successful
**Screenshots**

**Version (please complete the following information):**
Kali VM
Firefox

**Additional details**
install.sh / Docker compose output, log files or any other detail about the problem here.

**Comment by 0x0FB0** [comment]
Can you make sure `db.env` file have been created with credentials inside?
Try this:
```
# docker-compose down

# docker-compose build db

# docker-compose up
```

**Comment by mrdavi5** [comment]
still same issue:

root@kali:/opt/pulsar# more db.env 
MYSQL_RANDOM_ROOT_PASSWORD=yes
MYSQL_DATABASE=pulsar
MYSQL_USER=pulsar_db_user
MYSQL_PASSWORD=0052ef3ae4287e19b4f4a96e
root@kali:/opt/pulsar# docker-compose down
Stopping web     ... done
Stopping sandbox ... done
Stopping db      ... done
Stopping queue   ... done
Removing web     ... done
Removing sandbox ... done
Removing db      ... done
Removing queue   ... done
Removing network pulsar_default
root@kali:/opt/pulsar# docker-compose build db
Building db
Step 1/4 : FROM mysql:8.0.18
 ---> ed1ffcb5eff3
Step 2/4 : COPY conf/mysqld.cnf /etc/mysql/my.cnf
 ---> Using cache
 ---> bacf7cb598b6
Step 3/4 : RUN mkdir /var/log/mysql
 ---> Using cache
 ---> 020c56ed6df3
Step 4/4 : RUN chown mysql /var/log/mysql
 ---> Using cache
 ---> 445a42bdd7fd
Successfully built 445a42bdd7fd
Successfully tagged pulsar_db:latest




web        | The above exception was the direct cause of the following exception:
web        | 
web        | Traceback (most recent call last):
web        |   File "manage.py", line 22, in <module>
web        |     main()
web        |   File "manage.py", line 18, in main
web        |     execute_from_command_line(sys.argv)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
web        |     utility.execute()
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
web        |     self.fetch_command(subcommand).run_from_argv(self.argv)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
web        |     self.execute(*args, **cmd_options)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
web        |     self.check()
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
web        |     all_issues = self._run_checks(
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
web        |     return checks.run_checks(**kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
web        |     new_errors = check(app_configs=app_configs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/model_checks.py", line 34, in check_all_models
web        |     errors.extend(model.check(**kwargs))
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1275, in check
web        |     *cls._check_constraints(),
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1841, in _check_constraints
web        |     connection.features.supports_table_check_constraints or
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
web        |     res = instance.__dict__[self.name] = self.func(instance)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/features.py", line 93, in supports_column_check_constraints
web        |     if self.connection.mysql_is_mariadb:
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
web        |     res = instance.__dict__[self.name] = self.func(instance)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 363, in mysql_is_mariadb
web        |     return 'mariadb' in self.mysql_server_info.lower()
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
web        |     res = instance.__dict__[self.name] = self.func(instance)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 350, in mysql_server_info
web        |     with self.temporary_connection() as cursor:
web        |   File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
web        |     return next(self.gen)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 604, in temporary_connection
web        |     with self.cursor() as cursor:
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 260, in cursor
web        |     return self._cursor()
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 236, in _cursor
web        |     self.ensure_connection()
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web        |     self.connect()
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
web        |     raise dj_exc_value.with_traceback(traceback) from exc_value
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web        |     self.connect()
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
web        |     self.connection = self.get_new_connection(conn_params)
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 233, in get_new_connection
web        |     return Database.connect(**conn_params)
web        |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 84, in Connect
web        |     return Connection(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 171, in __init__
web        |     super(Connection, self).__init__(*args, **kwargs2)
web        | django.db.utils.OperationalError: (1045, "Access denied for user 'pulsar_db_user'@'web.pulsar_default' (using password: YES)")
web        | Traceback (most recent call last):
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web        |     self.connect()
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
web        |     self.connection = self.get_new_connection(conn_params)
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 233, in get_new_connection
web        |     return Database.connect(**conn_params)
web        |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 84, in Connect
web        |     return Connection(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 171, in __init__
web        |     super(Connection, self).__init__(*args, **kwargs2)
web        | MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'pulsar_db_user'@'web.pulsar_default' (using password: YES)")
web        | 
web        | The above exception was the direct cause of the following exception:
web        | 
web        | Traceback (most recent call last):
web        |   File "manage.py", line 22, in <module>
web        |     main()
web        |   File "manage.py", line 18, in main
web        |     execute_from_command_line(sys.argv)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
web        |     utility.execute()
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
web        |     self.fetch_command(subcommand).run_from_argv(self.argv)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
web        |     self.execute(*args, **cmd_options)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
web        |     self.check()
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
web        |     all_issues = self._run_checks(
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 63, in _run_checks
web        |     issues = run_checks(tags=[Tags.database])
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
web        |     new_errors = check(app_configs=app_configs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/database.py", line 10, in check_database_backends
web        |     issues.extend(conn.validation.check(**kwargs))
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/validation.py", line 9, in check
web        |     issues.extend(self._check_sql_mode(**kwargs))
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/validation.py", line 13, in _check_sql_mode
web        |     with self.connection.cursor() as cursor:
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 260, in cursor
web        |     return self._cursor()
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 236, in _cursor
web        |     self.ensure_connection()
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web        |     self.connect()
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
web        |     raise dj_exc_value.with_traceback(traceback) from exc_value
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web        |     self.connect()
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
web        |     self.connection = self.get_new_connection(conn_params)
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 233, in get_new_connection
web        |     return Database.connect(**conn_params)
web        |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 84, in Connect
web        |     return Connection(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 171, in __init__
web        |     super(Connection, self).__init__(*args, **kwargs2)
web        | django.db.utils.OperationalError: (1045, "Access denied for user 'pulsar_db_user'@'web.pulsar_default' (using password: YES)")
web        | 
web        | [+] Collecting static files...
web        | 
web        | 
web        | 163 static files copied to '/portal/staticfiles', 43 unmodified.
web        | 
web        | [+] Starting Nginx web server...
web        | 
web        | Starting nginx: nginx.
web        | 
web        | [+] Starting pulsar on https://localhost:8443/
web        |                                                                                                                                               
web        |     It can take a while to boot.
web        | 
web        | [2020-04-06 13:52:53 +0000] [74] [INFO] Starting gunicorn 20.0.4
web        | [2020-04-06 13:52:53 +0000] [74] [INFO] Listening at: unix:/tmp/run/gunicorn.sock (74)
web        | [2020-04-06 13:52:53 +0000] [74] [INFO] Using worker: sync
web        | [2020-04-06 13:52:53 +0000] [76] [INFO] Booting worker with pid: 76

**Comment by 0x0FB0** [comment]
Checking..

**Comment by 0x0FB0** [comment]
In the meantime, you may want to try again with `docker-compose build --no-cache`

**Comment by 0x0FB0** [comment]
Can you verify if database credentials have been configured?
```
p=`cat db.env | grep MYSQL_PASSW | cut -d '=' -f 2`; docker-compose exec db mysql -u pulsar_db_user --password=$p -e 'USE pulsar; SHOW TABLES'
```

**Comment by mrdavi5** [comment]
Tried doing a --no-cache still same issue. 

root@kali:/opt/pulsar# p=`cat db.env | grep MYSQL_PASSW | cut -d '=' -f 2`; docker-compose exec db mysql -u pulsar_db_user --password=$p -e 'USE pulsar; SHOW TABLES'
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'pulsar_db_user'@'localhost' (using password: YES)

**Comment by 0x0FB0** [comment]
I'm able to recreate your issue, whatever happened during the installation (runned it multiple times?) db.env changed after building containers, and now db has the old password, django app have a new one.

### Modified **db.env**:
```
MYSQL_RANDOM_ROOT_PASSWORD=yes
MYSQL_DATABASE=pulsar
MYSQL_USER=pulsar_db_user
MYSQL_PASSWORD=NEW_PASSWORD_NOT_BUILT_WITH

```

### MySQL connection error, just as yours:
```
| MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'pulsar_db_user'@'web.pulsar_default' (using password: YES)")
web        | 
web        | The above exception was the direct cause of the following exception:
web        | 
web        | Traceback (most recent call last):
web        |   File "manage.py", line 22, in <module>
web        |     main()
web        |   File "manage.py", line 18, in main
web        |     execute_from_command_line(sys.argv)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
web        |     utility.execute()
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
web        |     self.fetch_command(subcommand).run_from_argv(self.argv)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
web        |     self.execute(*args, **cmd_options)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
web        |     self.check()
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
web        |     all_issues = self._run_checks(
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 63, in _run_checks
web        |     issues = run_checks(tags=[Tags.database])
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
web        |     new_errors = check(app_configs=app_configs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/database.py", line 10, in check_database_backends
web        |     issues.extend(conn.validation.check(**kwargs))
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/validation.py", line 9, in check
web        |     issues.extend(self._check_sql_mode(**kwargs))
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/validation.py", line 13, in _check_sql_mode
web        |     with self.connection.cursor() as cursor:
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 260, in cursor
web        |     return self._cursor()
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 236, in _cursor
web        |     self.ensure_connection()
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web        |     self.connect()
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
web        |     raise dj_exc_value.with_traceback(traceback) from exc_value
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web        |     self.connect()
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
web        |     self.connection = self.get_new_connection(conn_params)
web        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web        |     return func(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 233, in get_new_connection
web        |     return Database.connect(**conn_params)
web        |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 84, in Connect
web        |     return Connection(*args, **kwargs)
web        |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 171, in __init__
web        |     super(Connection, self).__init__(*args, **kwargs2)
web        | django.db.utils.OperationalError: (1045, "Access denied for user 'pulsar_db_user'@'web.pulsar_default' (using password: YES)")
```

My fresh clone is building just fine the first time so that's not a Pulsar problem itself, but a broken installation procedure.

The only solution I can see here is to start from scratch after removing all your pulsar containers:
> :warning: This command will delete all docker containers on your PC
```
# docker-compose down
# docker rm -f $(docker ps -a -q)
# cd ..
# rm -rf pulsar/
# git clone https://github.com/FooBallZ/pulsar
# cd pulsar/
# ./install.sh
```

Let me know if it still breaks after fresh install.

**Comment by mrdavi5** [comment]
Awesome, So I did a fresh install as per the commands above. Noticed I still couldn't log in to the front end but wasn't get the same errors in the start up logs. I then did :

# docker-compose down

# docker-compose build --no-cache db

# docker-compose up

then everything came up fine :) Now in the portal. Thanks!
