### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by emrahkocabuga** [FooBallZ/pulsar#26]
Hi,
I'm trying to install Pulsar on Centos but when it comes to the final stage, it stays on the screen below:

![Error1](https://user-images.githubusercontent.com/30760653/79041793-338b5b00-7bfb-11ea-90cf-00450fc71bdd.PNG)

And I'm later trying to connection through browser i receive these errors:

![Error2](https://user-images.githubusercontent.com/30760653/79041829-90871100-7bfb-11ea-8ef7-887bef463b72.PNG)

What should I do to fix this error, can you help?

        Operating System: CentOS Linux 7 (Core)
        CPE OS Name: cpe:/o:centos:centos:7
        Kernel: Linux 3.10.0-1062.18.1.el7.x86_64
        Architecture: x86-64

	centos-release-7-7.1908.0.el7.centos.x86_64

@FooBallZ

**Comment by 0x0FB0** [comment]
Check out this issue:
https://github.com/FooBallZ/pulsar/issues/25

**Comment by emrahkocabuga** [comment]
Hi,

Thank you for the quick return. I tried many times your proposed solutions in #25 but the result is the same.. problem still continues

![image](https://user-images.githubusercontent.com/30760653/79048238-4f572700-7c24-11ea-93a5-6584407c0217.png)

**Comment by 0x0FB0** [comment]
Make sure you are trying to access either `https://localhost:8443` or `https://127.0.0.1:8443`. Otherwise you will get a 400 error.

So far I can see that installation seems to be broken. Password in db.env is not the same as the one that containers were built with.

Have you ran install.sh more than once?

Can you send me output of your install.sh, so I can investigate?

**Comment by emrahkocabuga** [comment]
Hi,

Yes i'm sure, I trying the access attempt correctly. 

Yes I have ran install.sh more than once. But i before deleted containers completely and i fresh install docker then i tried.

I attached the install.sh output file.

[Pulsar_Install.txt](https://github.com/FooBallZ/pulsar/files/4464951/Pulsar_Install.txt)

**Comment by 0x0FB0** [comment]
Can you do:
```
# cat db.env
# docker-compose down
# docker-compose build --no-cache
# docker-compose up --force-recreate
# p=$(cat db.env | grep MYSQL_PASSW | cut -d '=' -f 2); docker-compose exec db mysql -u pulsar_db_user --password=$p -e 'USE pulsar; SHOW TABLES'
```
and send me the output?

**Comment by emrahkocabuga** [comment]
Hi,

I attached the Pulsar_Output.txt file.

[Pulsar_Output.txt](https://github.com/FooBallZ/pulsar/files/4465951/Pulsar_Output.txt)

**Comment by 0x0FB0** [comment]
Ok, you've stopped it with ^C but I saw migrations were successfull so It should work now.

do 
```
docker-compose down
docker-compose up --force-recreate
```

And it will be working.

**Comment by emrahkocabuga** [comment]
Hi,

I did not stop the running process. The process stopped again on the screen at the last stage. Therefore I made ^C

I did something like this later: I installed fresh centos os and i did again installation pulsar with install.sh
But the process stopped again on the screen at the last stage:
![image](https://user-images.githubusercontent.com/30760653/79069018-a536d800-7cd3-11ea-847f-ddaf4e7a2b47.png)

I ran this command you gave in a different session:
` p=$(cat db.env | grep MYSQL_PASSW | cut -d '=' -f 2); docker-compose exec db mysql -u pulsar_db_user --password=$p -e 'USE pulsar; SHOW TABLES'`

and result:
![image](https://user-images.githubusercontent.com/30760653/79069165-bcc29080-7cd4-11ea-9c57-e38da7e06f74.png)

What would you suggest me to do after this stage?

**Comment by 0x0FB0** [comment]
Open a browser and go to https://localhost:8443

**Comment by emrahkocabuga** [comment]
I get 400 error again:

![79041829-90871100-7bfb-11ea-8ef7-887bef463b72](https://user-images.githubusercontent.com/30760653/79069685-d49c1380-7cd8-11ea-8002-e0098cd12448.png)

**Comment by 0x0FB0** [comment]
Can you run:
```
# docker-compose exec web tail -f /var/log/nginx/error.log
# docker-compose exec web tail -f logs/django.log
```
try to access the web app and check if any error appear?

**Comment by emrahkocabuga** [comment]
I ran first code but it stopped on the screen and then i ran second code, result:
![image](https://user-images.githubusercontent.com/30760653/79070296-9523f600-7cdd-11ea-8074-e2bffcefeb80.png)

![79041829-90871100-7bfb-11ea-8ef7-887bef463b72](https://user-images.githubusercontent.com/30760653/79070361-0499e580-7cde-11ea-9cfa-93584ea2201c.png)

**Comment by 0x0FB0** [comment]
I've mentioned at the very beginning:
> Make sure you are trying to access either https://localhost:8443 or https://127.0.0.1:8443. Otherwise you will get a 400 error.

See TRUBLESHOOTING.md
For external access you will need to configure ALLOWED_HOSTS and rebuild containers.
