### ISSUE TITLE
Create user and pass for gui

### ISSUE THREAD

**Issue by meetgyn** [FooBallZ/pulsar#27]
How to create username and password to access the home page :?

**Comment by 0x0FB0** [comment]
It is generated at the very beginning of the installation, see installation guide in README.md.

In case you would like to add it after the installation, you can do it in Django administration portal, just go to https://localhost:8443/admin/portaluser/add

**Comment by meetgyn** [comment]
it didn't work, I get in the address and I get a 404 error
