### ISSUE TITLE
ARM/RPI4 Support

### ISSUE THREAD

**Issue by wh1tenoise** [FooBallZ/pulsar#28]
Would it be possible to support the ARM platform? A RPI4 should be powerful enough to run this.

After quickly looking into it, a change from MySQL to MariaDB should suffice. Sadly, MySQL does not offer a ARM-Docker-image yet.

**Comment by 0x0FB0** [comment]
I'll check what can be done. As I needed an exact mysql image version, I'm almost sure it wont be the case of changing the image name.
I encourage you to also try to set it up.
I'll let you know once I've tested it.

**Comment by wh1tenoise** [comment]
Thanks for the feedback!

Just to make a now expected debugging easier: Why did you need a specific version of MySQL? Any other limitations that might hinder the port to the ARM platform?

**Comment by 0x0FB0** [comment]
There was a problem with authentication method compability with django/celery.

btw. Are you sure your RPI will handle it? Minimal requirements are 8G of memory.

Sorry, i had no time to look bintobit yet. Will try it on the weekend.

**Comment by 0x0FB0** [comment]
OK

It seems that it the end you just need to change contents of `./db_storage/Dockerfile` to:

```
FROM mariadb
# nothing else
```


remember to rebuild everything, so:

```
# docker-compose build --no-cache
# docker-compose up --force-recreate
```

Try that and let me know how it runs.
