### ISSUE TITLE
Mac compatibility issues during installation

### ISSUE THREAD

**Issue by vectorinfosec** [FooBallZ/pulsar#3]
after installation i got error 

500 error

```
web        | django.db.utils.OperationalError: (1045, 'Plugin caching_sha2_password could not be loaded: /usr/lib/x86_64-linux-gnu/mariadb19/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory')

```

**Comment by 0x0FB0** [comment]
Ok, 
I've encountered the same issue, but in logs I've noticed also access errors to MySQL service.
It seems it occurred because of bad characters in MySQL password generator.

https://github.com/FooBallZ/pulsar/commit/896af47b60b9353a8a9b3ff35a27979821fa2bba
I've updated the master branch. 
Can you clone again and attempt a fresh install?

**Comment by vectorinfosec** [comment]
I tried to install again with latest clone. still got same issue

**Comment by vectorinfosec** [comment]
I face this error

```
'Plugin caching_sha2_password could not be loaded:
```

**Comment by 0x0FB0** [comment]
Can you send me your installation (docker-compose build) output?
So far I am unable to recreate the issue.
Most probably I'll need to set version-fixed apt install.

btw. What host OS are you using?

**Comment by abuvanth** [comment]
[docker_compose_build.log](https://github.com/FooBallZ/pulsar/files/4329292/docker_compose_build.log)


My host os is mac mojave 10.14.6

**Comment by 0x0FB0** [comment]
Just in case, I've fixed apt package versions in Dockerfile
https://github.com/FooBallZ/pulsar/commit/4a04f8d1860e997ebf969d4c7360b3d81bad4e77

**Comment by vectorinfosec** [comment]
My host os is mac mojave.

[amqp_error.txt](https://github.com/FooBallZ/pulsar/files/4329446/amqp_error.txt)

**Comment by 0x0FB0** [comment]
Ok, that looks as a different issue now.
From the output I can tell that web service cannot authenticate to RabbitMQ.
This is a certificate authentication, can you check if the certificate file have been generated during installation?
```
# ls queue_storage/client_cert/
cacert.pem  cert.pem  key.pem  key-store.p12  req.pem  trust-store.p12
```
also, can you send celery.log output? (please use "attach files" option)
```
# docker-compose exec web cat logs/celery.log
```
This should provide much more information.
I've never tested it on MacOS yet, thanks for the feedback!

**Comment by 0x0FB0** [comment]
I'll test it on mac this weekend

**Comment by 0x0FB0** [comment]
I've successfully tested it on macOS Mojave 10.14.5 and was not able to recreate the issue.
However, there were still some issues with password generation and special characters.
For me it produced kombu "bad port number" error which shows that password parser in kombu has weird behavior. I think it is close to your issue, it might be that it took it as sha256 hash formatted and hence your error.

Please try it with latest commit:
https://github.com/FooBallZ/pulsar/commit/04d696d73762e4160b6c1a0898c8ff66953490c4

If you still have any issues, please send me some logs so I can investigate.

**Comment by vectorinfosec** [comment]
I attached docker compose log

[docker_compose.log](https://github.com/FooBallZ/pulsar/files/4331706/docker_compose.log)

**Comment by 0x0FB0** [comment]
It looks like your db password configuration is bad, can be that it is still built with the cached old one.
Bare in mind that in order to refresh your github clone you need to rebuild containers.
Try running `./install.sh` again or better:
```
docker-compose down
docker-compose build --no-cache
docker-compose up --force-recreate
```

**Comment by vectorinfosec** [comment]
working fine now. thanks

**Comment by 0x0FB0** [comment]
Great news!
In case of further issues let me know.
