### ISSUE TITLE
db migrations - access denied

### ISSUE THREAD

**Issue by 98max1** [FooBallZ/pulsar#32]
> :warning: Make sure you have seen TROUBLESHOOTING.md

**Describe the bug**
I'm doing a clean install following you'r stated commands from issue#25
Yet, i'm still getting these access denied messages and when go to https://localhost:8443/ , i get error 500.
All the .env files contain information
Tried connection to the db with the db.env creedentials but no luck.
(docker-compose exec db mysql -u pulsar_db_user --password="IaP+v3elMDpH~Ej2\1" -e 'USE pulsar; SHOW TABLES')

**To Reproduce**
1 docker-compose down
2 docker rm -f $(docker ps -a -q)
3 cd ..
4 rm -rf pulsar/
5 git clone https://github.com/FooBallZ/pulsar
6 cd pulsar/
7 ./install.sh

**Expected behavior**
Logged in

**Version (please complete the following information):**
 - Windows 10
 - docker version 19.03.8, build afacb8b
 - docker-compose version 1.25.4, build 8d51620a

**Additional details**
pulsar_error.txt / contains error output
[pulsar_error.txt](https://github.com/FooBallZ/pulsar/files/4536313/pulsar_error.txt)

**Comment by 0x0FB0** [comment]
Issue emerges like 8th time already.
in order to propery rebuild containers after change of *.env files you need to use:
```
# docker-compose build --no-cache
# docker-compose up --force-recreate
```
Or just clone it again, I've made a change that will fix tthis confusion once for all.
