### ISSUE TITLE
216.58.200.241:443: i/o timeout

### ISSUE THREAD

**Issue by yunhaodexiao** [FooBallZ/pulsar#34]
Step 23/32 : RUN cd zdns/zdns && go build .
---> Running in a1095150e4e3
go: github.com/asergeyev/nradix@v0.0.0-20170505151046-3872ab85bb56: Get https://proxy.golang.org/github.com/asergeyev/nradix/@v/v0.0.0-20170505151046-3872ab85bb56.mod: dial tcp 216.58.200.241:443: i/o timeout

Execute this IO timeout, I use the Internet in Hong Kong @FooBallZ

**Comment by 0x0FB0** [comment]
Have you tried to ping proxy.golang.org?

In case you cannot connect to it, you might want to download zdns from different source.
Just edit `sandbox_storage/Dockerfile` file and modify those lines accordingly:
```
RUN git clone https://github.com/zmap/zdns
RUN cd zdns/zdns && go build .
RUN ln -s /opt/zdns/zdns/zdns /bin/zdns
```

Your internet connection is not my problem, or a global one.
