### ISSUE TITLE
Failed to build docker containers

### ISSUE THREAD

**Issue by areblitz04** [FooBallZ/pulsar#36]
Hi, I'm trying to install Pulsar on Kali Linux 2020 version, but when building the Docker containers (Sandbox), I get an error like this.

![image](https://user-images.githubusercontent.com/63386537/81891561-b85cf200-9576-11ea-8c88-f56469409110.png)

The same error goes for installation in Ubuntu 18.04 LTS. 
My Docker version is 19.03.8
My Docker-compose version is 1.25.5

@FooBallZ

**Comment by 0x0FB0** [comment]
Thanks for the heads-up!
Needed to update go to v1.14.
Should work now.

**Comment by 0x0FB0** [comment]
Too soon, working on it..

**Comment by 0x0FB0** [comment]
Looks good now.
@areblitz04 Let me know if it works on your end.
