### ISSUE TITLE
🐛Installation error

### ISSUE THREAD

**Issue by Aajnow** [FooBallZ/pulsar#37]
Although I have the 1.1 version of libsss-dev installed. It still thorws this error
![image](https://user-images.githubusercontent.com/10479886/82129373-4a613680-97d3-11ea-8dca-6a43c0c26bb8.png)

OS:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

**Comment by 0x0FB0** [comment]
It seems that apt repository have changed. ¯\_(ツ)_/¯
Made necessary changes, try again with a fresh clone and let me know.

**Comment by Aajnow** [comment]
Thanks for the quick turnaround.
Fixed it!.
Closing
