### ISSUE TITLE
🐛Sir localhost not run 

### ISSUE THREAD

**Issue by ALiHassan420** [FooBallZ/pulsar#43]
> :warning: Make sure you have seen TROUBLESHOOTING.md before sending this issue request!

**Describe the bug**
[ A clear and concise description of what the bug is. ]

**To Reproduce**
[ Steps to reproduce the behavior. ]

**Expected behavior**
[ A clear and concise description of what you expected to happen. ]

**Screenshots**
[ If applicable, add screenshots to help explain your problem. ]

**Version (please complete the following information):**
 - OS: [e.g. Windows 10, Debian 9]
 - Browser [e.g. chrome, firefox]
 - Browser version [e.g. 22]
 - Docker version [docker -v]
 - Docker compose version [docker-compose -v]

**Additional details**
[ install.sh / Docker compose output, log files or any other detail about the problem here. ]

**Comment by 0x0FB0** [comment]
Should build fine now
