### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by asdadasdaa** [FooBallZ/pulsar#48]
Version :
OS: kali 2021.1
Docker version [docker -v] :Docker version 20.10.5
Docker compose version [docker-compose -v] : docker-compose version 1.25.5
pip : 21.0.1
Rustc  1.50.0
![image](https://user-images.githubusercontent.com/69138564/110449294-068e4380-80fd-11eb-88bc-268e207d95b6.png)

**Comment by 0x0FB0** [comment]
Should build fine now. There were multiple changes in dependencies that needed to be addressed.
