### ISSUE TITLE
🐛Docker-compose build error

### ISSUE THREAD

**Issue by ghost** [FooBallZ/pulsar#53]
Hi, 

When try to build the docker img I have the following error.

ERROR [ 4/15] RUN apt-get update && apt-get install -y --allow-downgrades libssl1.1 libgnutls30 libcurl4 libpython3.7-minimal libcurl4-open  7.3s
------                                                                                                                                                 
 > [ 4/15] RUN apt-get update && apt-get install -y --allow-downgrades libssl1.1 libgnutls30 libcurl4 libpython3.7-minimal libcurl4-openssl-dev python3.7-minimal python3-minimal mime-support libmpdec2 libpython3.7-stdlib=3.7.3-2+deb10u2 python3.7=3.7.3-2+deb10u2 libpython3-stdlib python3 less sensible-utils bzip2 libmagic-mgc libmagic1 file krb5-locales manpages netcat-traditional ucf xz-utils libapr1 libaprutil1 apache2-utils binutils-common libbinutils binutils-x86-64-linux-gnu binutils libisl19 libmpfr6 libmpc3 cpp-8 cpp python3-lib2to3 python3-distutils dh-python fonts-dejavu-core fontconfig-config libcc1-0 libgomp1 libitm1 libatomic1 libasan5 liblsan0 libtsan0 libubsan1 libmpx2 libquadmath0 libgcc-8-dev gcc-8 gcc geoip-database libbsd0 libc-dev-bin linux-libc-dev libc6-dev libkeyutils1 libkrb5support0 libk5crypto3 libkrb5-3 libgssapi-krb5-2 libsasl2-modules-db libsasl2-2 libldap-common libldap-2.4-2 libnghttp2-14 libpsl5 librtmp1 libssh2-1 libevent-2.1-6 libexpat1-dev libpng16-16 libfreetype6 libfontconfig1 libjpeg62-turbo libjbig0 libwebp6 libtiff5 libxau6 libxdmcp6 libxcb1 libx11-data libx11-6 libxpm4 libgd3 libgeoip1 libgmpxx4ldbl libgmp-dev libunbound8 libgnutls-dane0 libgnutls-openssl27 libgnutlsxx28 libidn2-dev libp11-kit-dev libtasn1-6-dev nettle-dev libgnutls28-dev libicu63 mysql-common mariadb-common libmariadb3 zlib1g-dev libmariadb-dev lsb-base nginx-common libnginx-mod-http-auth-pam libxml2 libxslt1.1 libnginx-mod-http-dav-ext libnginx-mod-http-echo libnginx-mod-http-geoip libnginx-mod-http-image-filter libnginx-mod-http-subs-filter libnginx-mod-http-upstream-fair libnginx-mod-http-xslt-filter libnginx-mod-mail libnginx-mod-stream libpython3.7 libpython3.7-dev libpython3-dev libsasl2-modules libssl-dev libtasn1-doc libutempter0 manpages-dev netcat nginx-full nginx publicsuffix python3.7-dev python3-dev screen openssh-client procps:
#8 0.696 Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
#8 0.713 Get:2 http://deb.debian.org/debian buster InRelease [121 kB]
#8 0.818 Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
#8 1.014 Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [269 kB]
#8 1.266 Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
#8 3.222 Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [9504 B]
#8 4.022 Fetched 8424 kB in 3s (2426 kB/s)
#8 4.022 Reading package lists...
#8 5.152 Reading package lists...
#8 6.251 Building dependency tree...
#8 6.741 Reading state information...
#8 7.135 E: Version '3.7.3-2+deb10u2' for 'libpython3.7-stdlib' was not found
#8 7.137 E: Version '3.7.3-2+deb10u2' for 'python3.7' was not found

**Comment by 0x0FB0** [comment]
Should be ok now, in case of further issues check out the version with exported docker containers in releases section
